### PR TITLE
Relaxed polymorphic variant error type constraint

### PR DESCRIPTION
**Pull request by KKostya**
Following this article  https://keleshev.com/composable-error-handling-in-ocaml and discussion in #ocaml channel. 
I propose to use approach `D. Result type with polymorphic variants for errors` for error handling.

### CODE REVIEW

**Comment by aidmandorky** [comment]
LGTM unless @actionshrimp  has something to say otherwise?

**Comment by aidmandorky** [comment]
While we're on this topic, do you think it makes sense to have these as polymorphic variants as well? https://github.com/imandra-ai/imandra-http-api-client/blob/kostya/polyvariant-errors/src/api.ml#L10-L12

**Comment by actionshrimp** [comment]
Cool looks good to me too.
 
Not sure I see the need to swap `type syntax` over to be a poly variant right now though? Are you thinking it would just make it slightly easier to construct requests?

Also, just a reminder that if you do change anything in the `api.ml` file in the future: it's copied over from the same file in the api-server part of `imandra`, so we'll need to update it on that side too. Shouldn't be a problem to do so, just worth bearing in mind :)

**Comment by aidmandorky** [comment]
Yeah, I just was wondering about `type syntax` since the swagger ocaml library generated them as poly variants, but its not needed for now, sure.

**Review by aidmandorky — APPROVED** [review]

**Pull request merged**
